# client role is deprecated. Use ceph_common.yml instead
classes:
- system.ceph.client.container
- system.ceph.monitoring.cluster_stats
pillars:
  docker:
    client:
      stack:
        monitoring:
          service:
            remote_agent:
              volumes:
                - ${ceph:client:prefix_dir}/etc/ceph:/etc/ceph
